#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorR,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorL,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//tento program je pro autonomni bear rescue pro robata 'medved'




float distance; //vzdalenost co vidi senzor
float constant; //konstanta mezi hodnotami senzoru a mm
float wheel_base = 220; //rozvor kol robota
float wheel_diameter = 130; //prumer kol robota
int speed = 100; //rychlost motoru




void buttons(){
	while(true){
		if(getButtonPress(buttonUp)==1)//pokud se zmackne tlacitko nahoru zacne robot hledat medveda v hristy
			{
			esko();
			bear_search_left_sensor(200);

			}
				if(getButtonPress(buttonDown)==1)//pokud se zmackne tlacitko nahoru zacne robot hledat medveda v rohu
				{
				esko();


				}
					if(getButtonPress(buttonLeft)==1)//pokud se zmackne tlacitko nahoru zacne robot hledat medveda u zdi
				{
				esko();


				}







	}
}


void forward(short lenght) //delka co ma robot ujet v mm
{
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorB);
	moveMotorTarget(motorA, lenght*360/3.14159*wheel_diameter, speed);
	moveMotorTarget(motorB, lenght*360/3.14159*wheel_diameter, speed);
	waitUntilMotorStop(motorA);
	waitUntilMotorStop(motorB);
}

void turn(float turnindeg)//o kolik se ma otocit robot ve stupnich
{
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorB);
	moveMotorTarget(motorA, turnindeg*wheel_base/wheel_diameter, speed);
	moveMotorTarget(motorB, turnindeg*wheel_base/wheel_diameter, -speed);
	waitUntilMotorStop(motorA);
	waitUntilMotorStop(motorB);
}

void forward1(short stopdistance) //vzdalenost od zdi kdy robot zastavi
{
	int distance = getUSDistance(S1);
	setMotorSpeed(motorA, speed);
	setMotorSpeed(motorB, speed);
	while(distance>stopdistance*constant){
		distance = getUSDistance(S1);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance);
		delay(1);}
}

void bear_search_left_sensor(short wall_distance){ //vzdalenost od robota ke zdi
int distance2 = getUSDistance(S2);
setMotorSpeed(motorA, speed);
setMotorSpeed(motorB, speed);
		while(distance2<wall_distance){
		distance2 = getUSDistance(S2);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance2);
		delay(1);
		}
}
void bear_search_front_sensor(short wall_distance){ //vzdalenost od robota ke zdi
int distance1 = getUSDistance(S2);
setMotorSpeed(motorA, speed);
setMotorSpeed(motorB, speed);
		while(distance1<wall_distance){
		distance1 = getUSDistance(S2);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance1);
		delay(1);
		}
}

void grab_bear(){
forward(-5);
turn(90);




}
void esko(){//program na projeti eska doplnit konstany!!!!!!!!
forward1(10);
turn(90);
forward1(10);
turn(90);
forward1(20);
turn(-90);
forward(800);//vzdalenost na zacatek prostoru s medvedem
}






task main()
{





}
