#pragma config(Sensor, S1,     front,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     left,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     back,           sensorEV3_Touch, modeEV3Bump)
#pragma config(Motor,  motorA,          motorR,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          motorL,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          klepetoL,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          klepetoR,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float wheel_base = 200; //rozvor kol robota
const float wheel_diameter = 140; //prumer kol robota
int speed = 20; //rychlost motoru
int speed_k = 20;
float g_distanceir;








void close_klepeto(short open_deg){//o kolik stupnu se otevre klepeto
resetMotorEncoder(klepetoR);
resetMotorEncoder(klepetoL);
moveMotorTarget(klepetoR, open_deg,-20);
delay(50);
moveMotorTarget(klepetoL, open_deg,-20);
waitUntilMotorStop(klepetoR);
waitUntilMotorStop(klepetoL);
delay(10);
}
void open_klepeto(short open_deg){//o kolik stupnu se otevre klepeto
resetMotorEncoder(klepetoR);
resetMotorEncoder(klepetoL);
moveMotorTarget(klepetoR, open_deg, speed_k);
delay(50);
moveMotorTarget(klepetoL, open_deg, speed_k);
waitUntilMotorStop(klepetoR);
waitUntilMotorStop(klepetoL);
delay(10);
}
#include "senzory.h"

//tento program je pro autonomni bear rescue pro robata 'medved'




void turn(short turnindeg, short speedL, short speedR)//o kolik se ma otocit robot ve stupnich
{
	resetMotorEncoder(motorL);
	resetMotorEncoder(motorR);
	moveMotorTarget(motorL, turnindeg*wheel_base/wheel_diameter, speedL);
	moveMotorTarget(motorR, turnindeg*wheel_base/wheel_diameter, speedR);
	waitUntilMotorStop(motorL);
	waitUntilMotorStop(motorR);
	delay(10);
}

void turn_by_wall(short lenght, short speedL, short speedR){
	resetMotorEncoder(motorL);
	resetMotorEncoder(motorR);
	moveMotorTarget(motorL, lenght*360/(PI*wheel_diameter), speedL);
	waitUntilMotorStop(motorL);
	moveMotorTarget(motorR, lenght*360/(PI*wheel_diameter), speedR);
	waitUntilMotorStop(motorR);
	delay(10);
}

void forward1(short lenght) //delka co ma robot ujet v mm
{
	resetMotorEncoder(motorL);
	resetMotorEncoder(motorR);
	moveMotorTarget(motorL, lenght*360/(PI*wheel_diameter), speed);
	moveMotorTarget(motorR, lenght*360/(PI*wheel_diameter), speed);
	waitUntilMotorStop(motorL);
	waitUntilMotorStop(motorR);
	delay(10);
}

void backward1(short lenght) //delka co ma robot ujet v mm
{
	resetMotorEncoder(motorL);
	resetMotorEncoder(motorR);
	moveMotorTarget(motorL, lenght*360/(PI*wheel_diameter), -speed);
	moveMotorTarget(motorR, lenght*360/(PI*wheel_diameter), -speed);
	waitUntilMotorStop(motorL);
	waitUntilMotorStop(motorR);
	delay(10);
}
#include "roh.h"





void esko(){//program na projeti eska
forward1(900);
turn(90,20,-20);
forward1(400);
turn(90,20,-20);
forward1(550);
turn(90,-20,20);
forward1(480);
turn(90,-20,20);
forward1(200);
}

bool g_touch;

void buttons(){
	while(true){
		if(getButtonPress(buttonUp)==1)//pokud se zmackne tlacitko nahoru zacne robot hledat medveda v hristy
			{
			//esko();
			search_wall_end();
			delay(100);
			forward1(300);
			bearserch();
			turn(90,-20,20);
		open_klepeto(90);
		setMotorSpeed(motorR, -speed);
  	setMotorSpeed(motorL, -speed);
  	while(getTouchValue(back) == 0){
  	}
  		stopAllMotors();
			forward1(1080);



			//
			//turn(90,-20,20);
			//turn_by_wall(180,-80,80);
			//backward1(15);
			close_klepeto(45);
			setMotorSpeed(motorR, -speed);
  setMotorSpeed(motorL, -speed);
  while(getTouchValue(back) == 0){

  }
  		stopAllMotors();
turn(120,20,-20);
setMotorSpeed(motorR, -speed);
  setMotorSpeed(motorL, -speed);
  while(getTouchValue(back) == 0){

  }
  		stopAllMotors();





}
				if(getButtonPress(buttonDown)==1)//pokud se zmackne tlacitko dolu zacne robot hledat medveda v rohu
				{
				//esko();
				search_wall_end();
				roh();



				}
					if(getButtonPress(buttonLeft)==1)//pokud se zmackne tlacitko nahoru zacne robot hledat medveda u zdi
				{
				//esko();
				turn_by_wall(180,-100,100);

				}
	}
}














task main()
{
buttons();
//while (true){

//g_distanceir = getUSDistance(S1);



//}
}
