#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorR,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorL,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//tento program je pro autonomni bear rescue pro robata 'medved'

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//short turndistance; //vzdalenost od zdi kdy robot zastavi mm
//float turnindeg; //otoceni robota ve stupnich
float distance; //vzdalenost co vidi senzor
float constant; //konstanta mezi hodnotami senzoru a mm
float wheel_base = 220; //rozvor kol robota
float wheel_diameter = 130; //prumer kol robota
int speed = 100; //rychlost motoru

void strait(short lenght) //delka co ma robot ujet v mm
{
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorB);
	moveMotorTarget(motorA, lenght*360/3.14159*wheel_diameter, speed);
	moveMotorTarget(motorB, lenght*360/3.14159*wheel_diameter, speed);
	waitUntilMotorStop(motorA);
	waitUntilMotorStop(motorB);
}

void turn(float turnindeg)//o kolik se ma otocit robot ve stupnich
{
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorB);
	moveMotorTarget(motorA, turnindeg*wheel_base/wheel_diameter, speed);
	moveMotorTarget(motorB, turnindeg*wheel_base/wheel_diameter, -speed);
	waitUntilMotorStop(motorA);
	waitUntilMotorStop(motorB);
}

void forward1(short stopdistance) //vzdalenost od zdi kdy robot zastavi
{
	SensorType[S1] = sensorEV3_Ultrasonic;
	distance = getUSDistance(S1);
	setMotorSpeed(motorA, speed);
	setMotorSpeed(motorB, speed);
	while(distance>stopdistance*constant){
		distance = getUSDistance(S1);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance);
		delay(1);}
}

void bear_search(short wall_distance) //vzdalenost od robota ke zdi
{
	SensorType[S2] = sensorEV3_Ultrasonic;
	distance = getUSDistance(S2);
	setMotorSpeed(motorA, speed);
	setMotorSpeed(motorB, speed);
	while(distance<wall_distance){
		distance = getUSDistance(S2);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance);
		delay(1);}
}
void bear_search1(short wall_distance1) //hledani medveda pred robotem
	{
	SensorType[S1] = sensorEV3_Ultrasonic;
	distance = getUSDistance(S1);
	if(distance<wall_distance1)
	{
	SensorType[S1] = sensorEV3_Ultrasonic;
	distance = getUSDistance(S1);
	setMotorSpeed(motorA, speed);
	setMotorSpeed(motorB, speed);
	while(distance<wall_distance1){
		distance = getUSDistance(S1);
		displayBigTextLine(3, "vzdalenost: %.2f" , distance);
		delay(1);}
	}
	else
	{
	bear_search(2000);
	}
}
task bear_found(){



short wall_distance;

while(distance<wall_distance)
	{
	bool bearfound = true;
	stopTask(bear_found);
	}
}


task main()
{

startTask(bear_found);





forward1(200);
turn(90);
forward1(100);
turn(90);
forward1(300);
turn(-90);
forward1(200);
turn(90);
forward1(1200);
bear_search1(1400);
turn(90);
forward1(1);



}
